### PR TITLE
Add code coverage

### PR DESCRIPTION
**Pull request by max-sixty**
From https://github.com/xd009642/tarpaulin#travis-ci-and-coverage-sites

Closes https://github.com/rust-ndarray/ndarray/issues/618

### CODE REVIEW

**Comment by max-sixty** [comment]
Tests are passing now. Let me know any feedback.

IIUC someone with repo access will need to enable for coveralls in order to see & record the results

**Comment by LukeMathWalker** [comment]
Nice!
@jturner314, you enabled `codecov` for `ndarray-stats` - should we use the same account for all crates in this organization? Not familiar with the tool :raised_hands:

**Comment by termoshtt** [comment]
> IIUC someone with repo access will need to enable for coveralls in order to see & record the results

I've sent auth request for coveralls. @jturner314 could you check it?

> should we use the same account for all crates in this organization? 

I also try to use codecov for ndarray-linalg https://github.com/rust-ndarray/ndarray-linalg/pull/157 (though I still have some trouble about linking issue to LAPACK)

**Comment by max-sixty** [comment]
Just seen https://github.com/rust-ndarray/ndarray/pull/628! Fine to close this when the other merges.

**Comment by max-sixty** [comment]
Closing as stale; not sure whether the code on #628 was ever merged though?

**Pull request closed without merging**
