### PR TITLE
Implement Hash to be clippy compliant

### PR DESCRIPTION
**Pull request by alex179ohm**
Fix #642

### CODE REVIEW

**Comment by max-sixty** [comment]
@alex179ohm I see you doing lots - I'm a bit concerned that you're doing the same work that I've done in #642. Are you sure this is novel? (Great if it is!)

**Comment by alex179ohm** [comment]
Argh.. maybe the master branch is not in sync with the work you've done in the #642?

**Comment by max-sixty** [comment]
Right, that PR is not yet merged

**Comment by LukeMathWalker** [comment]
Given that we merge #642, should I close this? Or does it contain something that was missing there? @alex179ohm

**Comment by alex179ohm** [comment]
@LukeMathWalker  Close it, we switch to the #657. This issue has been completely merged with the work done by @max-sixty on the #642

**Pull request closed without merging**
