### PR TITLE
Use merge queue

### PR DESCRIPTION
**Pull request by bluss**
@adamreichold's recipe

* We don't run CI on the main branch at all any more because all commits are tested before being put there.
* Which tests are run is not differentiated by branch name but by event, either pull requests or merge queues.
* PR run should small and fast for quick feedback on proposed changes.
* Pre-merge checks should be complete so that the main branch is always is a known good state.

### CODE REVIEW

**Comment by bluss** [comment]
Wish me luck

**Comment by bluss** [comment]
Well, bad luck.

**Comment by adamreichold** [comment]
> Well, bad luck, it's supposed to run both yaml files for the merge queue 🤔

Are you sure merge queues are enabled?

**Comment by bluss** [comment]
yes, it used the merge queue for this one

**Comment by adamreichold** [comment]
It might be necessary to explicit configure the require CI workflows for merge queues in the branch protection rules (of the main branch).

**Comment by bluss** [comment]
There's a lot of unnecessary and unintiuitive caveats mentioned here https://stackoverflow.com/a/76740962  and hopefully that's the right track..

**Pull request merged**
