### PR TITLE
Prepare 0.15.5 release

### PR DESCRIPTION
**Pull request by jturner314**
Multiple users have requested a release with #1154. This PR prepares for a minimal 0.15.5 release. The `master` branch has some breaking changes, so I've cherry-picked the non-breaking changes to the 0.15.x branch.

- Cherry-pick non-breaking changes from master to 0.15.x.
- Update `RELEASES.md`.

### CODE REVIEW

**Comment by adamreichold** [comment]
@jturner314 Sorry being late to this PR, but I thought that #1151 would be part of the next 0.15.x maintenance release?

**Comment by jturner314** [comment]
Sorry, I missed that. I'll create a 0.15.6 release with #1151.

**Comment by jturner314** [comment]
@adamreichold I've released 0.15.6.

**Comment by adamreichold** [comment]
> @adamreichold I've released 0.15.6.

Thank you!

**Pull request merged**
