### PR TITLE
Run rustfmt and add to travis

### PR DESCRIPTION
**Pull request by cafeclimber**
Thought this was pretty low hanging fruit, but results in a...nasty looking commit (#597)

### CODE REVIEW

**Comment by LukeMathWalker** [comment]
It looks good to me :+1: Shall I merge? @jturner314 @bluss

**Comment by jturner314** [comment]
I would like to do this, but I'd like to finish merging some of the open PRs first to minimize merge conflicts. Then, we can re-run `cargo fmt`.

**Comment by LukeMathWalker** [comment]
Can you rebase this PR on `master` and re-run `cargo fmt` @cafeclimber? I'd like to merge this in before merging #628!

**Comment by LukeMathWalker** [comment]
Closing given #635 and #628.

**Pull request closed without merging**
