### PR TITLE
Fix ci

### PR DESCRIPTION
**Pull request by ZuseZ4**
Solving #828

### CODE REVIEW

**Comment by ZuseZ4** [comment]
@xd009642 I don't have the rights to merge this, but it should be fine if we agree to bump the MSRV to 1.42, I guess?
1.42 is the earliest version to allow fixing all lints from the current clippy version.

**Comment by xd009642** [comment]
I also don't have rights to merge but it looks good to me imo. I think maybe @jturner314 and @bluss are the two people to go to for approval + merge :eyes:

**Comment by xd009642** [comment]
@bluss @jturner314

**Comment by bluss** [comment]
Solid thanks

**Pull request merged**
