### PR TITLE
Refine PR #642

### PR DESCRIPTION
**Pull request by jturner314**
It took me a while to get back to this. It's just a few small changes (changing `clone_from_slice` to `copy_from_slice`, removing an outdated comment and changing `for` to `for_each` ([discussion](https://github.com/rust-ndarray/ndarray/pull/642#discussion_r305592799)), and changing range-based loops to iterator-based loops ([discussion](https://github.com/rust-ndarray/ndarray/pull/642#discussion_r305590788))).

### CODE REVIEW

**Comment by jturner314** [comment]
Oh, whoops, I didn't notice #657.

**Comment by max-sixty** [comment]
> Oh, whoops, I didn't notice #657.

No prob - we can close that one. Thanks for looking into the assembly!

**Comment by LukeMathWalker** [comment]
#657's changes are a subset of the changes in this PR - shall we merge this and close #657? @jturner314 @max-sixty

**Comment by max-sixty** [comment]
Yes perfect

**Pull request merged**
