### PR TITLE
Bump all dependencies

### LINKED ISSUE #765: Bump blas to 0.4.0
ndarray-linalg uses 0.4.0 too

### PR DESCRIPTION
**Pull request by Eijebong**
* Update blas-src to 0.6
* Update itertools to 0.9
* Update openblas-src to 0.9

Fixes #765

### CODE REVIEW

**Comment by termoshtt** [comment]
num-complex 0.3.0 has also released: https://github.com/rust-num/num-complex/releases/tag/num-complex-0.3.0

**Comment by nilgoyette** [comment]
With rayon, num-complex, approx + the three above, this PR is obsolete. What's the procedure? Replace this PR with another or nicely ask @Eijebong to update?

**Comment by cjordan** [comment]
Can I chime in naively - I forked `ndarray` just so I could bump its `num-complex` dependency, as another dependency was already using `num-complex` 0.3.0 and the different version apparently means that cargo refused to compile my project. So, is there any huge reason why `ndarray` should be restricted to 0.2.* or 0.3.*?  Could it just be 0.* instead?  I've noticed a similar problem for `rayon`.  In both cases, I did not see an API change so everything just worked fine.

**Comment by ZuseZ4** [comment]
@cjordan 
https://semver.org/

From what I know, specifying a dependency like done here (a.b.*) assures, that the project will always compile correctly.
By only specifying the major version a.*.* you may end up in a situation where one of your dependencies adds a pub function (or anything else) that you already implement in your own library. Cargo will pull the newest version that you allow. This might lead to nasty bugs where the runtime behavior silently changes, since the compiler adds the new implementation from your dependency, instead of your own one which has been used before.
Of course that's an unlucky situation and mostly won't happen, but the idea is to generally avoid such pitfalls by specifying the minor version too.
Please feel free to correct what I wrote in case that I got something wrong.

**Comment by mulimoen** [comment]
@ZuseZ4 You would only run into this problem when using glob imports, and this would be a compile time error at worst. You would not avoid this by specifying the minor version, this would simply mean all versions `>=major.minor` would be compatible with this crate, and minor bumps are allowed to add new functions.

@cjordan One has to specify `major` (or `0.minor`) to publish a crate

`ndarray` could use the bound `>=0.2.0, <0.4.0` for `num-complex` to allow either major version of `num-complex` if we require backwards compatability.

**Comment by bluss** [comment]
I would encourage a release to be made with this - I know I'm late to do it, but I will, if nobody else has time.

**Comment by xd009642** [comment]
@bluss yeah I'd like a release with what we currently have, a dependency update and also these small PRs to go in :smile: 

* https://github.com/rust-ndarray/ndarray/pull/848 
* https://github.com/rust-ndarray/ndarray/pull/847
* https://github.com/rust-ndarray/ndarray/pull/834

If you have time to look at ndarray that would be grand :grin:

**Comment by bluss** [comment]
Excellent @xd009642

**Pull request merged**
