### PR TITLE
Move changelog to a separate file

### PR DESCRIPTION
**Pull request by rth**
Hoping to help with https://github.com/rust-ndarray/ndarray/issues/670, this moves the changelog from the README to a separate file (`RELEASES.md` similarly to [rust repo](https://github.com/rust-lang/rust/blob/master/RELEASES.md) as it is getting quite long.

Also,
 - converts .rst to .md
 - Improve section titles (include date) for newer releases
 - Add some of the changes for 0.13 but clearly there is much more of those that can be addressed in a separate PR
 - Add subsections for 0.13 to better see new feature, API changes etc.

### CODE REVIEW

**Comment by LukeMathWalker** [comment]
I think this was long overdue given the size of our README :sweat_smile: 
I'd like to keep the latest release changelog in the README though (0.13 - to be released) - what do you think @rth?

**Comment by rth** [comment]
> I'd like to keep the latest release changelog in the README though (0.13 - to be released

Then maybe have it repeated both in the changelog and the readme? If there is a changelog, users are likely to look at it for the latest release as well?

**Comment by LukeMathWalker** [comment]
> > I'd like to keep the latest release changelog in the README though (0.13 - to be released
> 
> Then maybe have it repeated both in the changelog and the readme? If there is a changelog, users are likely to look at it for the latest release as well?

Duplicating it seems to be the best solution, I agree.

**Comment by LukeMathWalker** [comment]
Merging - we can then add the changelog for the latest release on the README before cutting `0.13`.

**Pull request merged**
