### PR TITLE
Add link to #rust-sci in README

### PR DESCRIPTION
**Pull request by jturner314**
It's helpful to have a place for users to chat. The link is to #rust-sci in the Mibbit client (the same client used for the "Mozilla IRC" link on https://www.rust-lang.org/community). Mibbit is nice because it provides a way for people to join the chat using their browser without even having to register.

### CODE REVIEW

**Comment by jturner314** [comment]
The Mozilla IRC server is [shutting down in the near future](http://exple.tive.org/blarg/2019/04/26/synchronous-text/), so we'll need to choose something other than #rust-sci on irc.mozilla.org. It looks like #rust-sci is migrating to oftc.net ([link to web chat](https://webchat.oftc.net?channels=rust-sci)), but let's wait a little while for things to stabilize before adding it to the README.

**Comment by ZuseZ4** [comment]
@bluss Shall we merge this?
It's not a breaking change, but I see no reason to keep it open, since it's just a doc change.

**Comment by bluss** [comment]
That channel has moved to matrix entirely, so I guess we'd like to link to matrix.

**Comment by jturner314** [comment]
I've changed this PR to provide a link to the Matrix room and the bridged IRC room on OFTC. (It's useful to provide a link to the IRC web chat so that users who don't want to go to the effort of creating a Matrix account can still ask a quick question.) [Click here to preview how GitHub renders the proposed README.](https://github.com/jturner314/ndarray/tree/irc-link)

**Review by bluss — APPROVED** [review]

**Pull request merged**
